[package]

name = "plex"
version = "0.0.1"
authors = ["Geoffry Song <goffrie@gmail.com>"]

homepage = "https://github.com/goffrie/plex"
repository = "https://github.com/goffrie/plex"
documentation = "http://goffrie.github.io/plex"
license = "MIT OR Apache-2.0"
keywords = ["tokenizer", "scanner", "lexer", "parser", "generator"]

[lib]

name = "plex"
plugin = true
crate-type = ["dylib"]

[dependencies.lalr]

version = "0.0.1"

[dependencies.redfa]

version = "0.0.1"
